version: '3.10'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile  # Assuming Dockerfile is in ./frontend directory
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile  # Assuming Dockerfile is in ./backend directory
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo  # Ensure backend service starts after the MongoDB service

  mongo:
    image: mongo  # Use the official MongoDB image from Docker Hub
    ports:
      - "27017:27017"
