# Use an official Python runtime as a parent image
FROM python:3.12

RUN apt-get update && apt-get install -y 


# Install Python dependencies
WORKDIR /app
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your application app
COPY . /app/
# Make port 8000 available to the world outside this container
EXPOSE 8000

# Set entry point or command to start your Django application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

